# Generated by Django 3.1 on 2020-10-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favCourse',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favGear',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favShop',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
