# Generated by Django 3.1 on 2020-10-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201030_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='compo',
            field=models.CharField(default='105', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favCourse',
            field=models.CharField(default='成木', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favShop',
            field=models.CharField(default='8823福生店', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frame',
            field=models.CharField(default='IMPULSO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wheel',
            field=models.CharField(default='Z LITE PBO pink', max_length=30, null=True),
        ),
    ]
